export const ROUTES = {
  home: '/',
  login: '/login',
  users: '/users',
  userAnalitic: '/users/:id',
  lunch: '/lunch',
  product: '/product',
  food: '/food',
  addFood: '/add-food',
  org: '/organisation',
  order: '/order',
  admins: '/admins',
  errorUrl: '/*',
  history: '/history',
};
