export const ROUTES = {
  home: '/',
  login: '/login',
  users: '/users',
  userAnalitic: '/users/:id',
  userOrders: '/user-orders/:id',
  lunch: '/lunch',
  lunchBase: '/lunch/:id',
  lunchAdd: '/lunch/add/:id',
  product: '/product',
  food: '/food',
  addFood: '/food/add',
  org: '/organisation',
  order: '/order',
  admins: '/admins',
  errorUrl: '/*',
  history: '/history',
  payments: '/payments',
  productLogs: '/product-logs',
  foodEdit: '/food/edit',
};
