export const ROUTES = {
  home: '/',
  login: '/login',
  users: '/users',
  userAnalitic: '/users/:id',
  lunch: '/lunch',
  lunchAdd: '/lunch/add',
  product: '/product',
  food: '/food',
  addFood: '/food/add',
  org: '/organisation',
  order: '/order',
  admins: '/admins',
  errorUrl: '/*',
  history: '/history',
  payments: '/payments',
  productLogs: '/product-logs',
};
