export const Endpoints = {
  Base: '/',
  Users: '/user/search-pagination',
  UsersMessage: '/user/send-message',
  UserStatus: '/user/status',
  UserOrganisation: '/user/org',
  UserChangeVerify: '/user/verify',
  UserPayment: '/user/payment',
  UserRole: '/user/role',
  Products: '/product',
  ProductAmount: '/product/amount',
  Foods: '/food',
  FoodUpdate: '/food/update',
  Organisation: '/org',
  OrganisationGroup: '/org',
  Order: '/order',
  Lunch: '/lunch',
  Login: '/admin/login',
  Admins: '/admin',
  History: '/trip',
  Payment: '/payment',
  ProductLogs: '/product-log',
};
