export const Endpoints = {
  Base: '/',
  Users: '/user',
  UsersMessage: '/user/send-message',
  UserStatus: '/user/status',
  UserOrganisation: '/user/org',
  UserChangeVerify: '/user/verify',
  UserPayment: '/user/payment',
  Products: '/product',
  ProductAmount: '/product/amount',
  Foods: '/food',
  Organisation: '/org',
  Order: '/order',
  Lunch: '/lunch',
  Login: '/admin/login',
  Admins: '/admin',
  History: '/trip',
};
